### ISSUE TITLE
Handling multiple fastqs in urls.list file during continuous download

### ISSUE THREAD

**Issue by SimonDMurray** [cellgeni/reprocess_public_10x#2]
Hi Alex,

I found a useful little tool that may be helpful for your reprocessing pipeline during the `continous_download.sh` section.

The following code takes a string containing multiple fastqs delimited by a ; and splits them into separate elements in an array:

```
#!/bin/bash

set -euo pipefail

# split up fastq files if there are more than one into an array

line="ftp.sra.ebi.ac.uk/vol1/fastq/SRR713/005/SRR7130925/SRR7130925_1.fastq.gz;ftp.sra.ebi.ac.uk/vol1/fastq/SRR713/005/SRR7130925/SRR7130925_2.fastq.gz"

if grep -q ";" <<< $line; then
  arrURL=(${line//;/ }) 
else
  arrURL=(${line})
fi

for URL in ${arrURL[@]}; do
  echo $URL
done
```

I hope this helps and obviously no pressure to include it!

Simon

**Comment by apredeus** [comment]
Totally missed this one! The URL list is always 1 file per line, so I don't think it should be necessary

Nevertheless, thank you Simon! :)
